version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    networks:
      - my_network
    depends_on:
      - mysql
    ports:
      - "9000:9000"

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_app
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www
    networks:
      - my_network
    depends_on:
      - backend

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge
    external: true

#docker run --name phpmyadmin --network my_network -p 8080:80 -e PMA_HOST=mysql -d phpmyadmin